#if UNITY_EDITOR
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace _Project.Scripts.Items
{
    public static class ItemTypeGenerator
    {
        [MenuItem("Tools/Regenerate ItemType Enum")]
        public static void Regenerate()
        {
            var settings = ItemTypeGeneratorSettings.GetOrCreate();
            var container = settings.Container;

            if (container == null)
            {
                Debug.LogError(
                    "[ItemTypeGenerator] SpreadsheetContainer не назначен. " +
                    "Откройте ItemTypeGeneratorSettings.asset и назначьте контейнер.");
                Selection.activeObject = settings;
                return;
            }

            var items = container.Content.ItemsData;
            if (items == null || items.Count == 0)
            {
                Debug.LogError("[ItemTypeGenerator] ItemsData пуст");
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by ItemTypeGenerator.");
            sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            sb.AppendLine("//     the code is regenerated.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace _Project.Scripts.Items");
            sb.AppendLine("{");
            sb.AppendLine("    public enum ItemType");
            sb.AppendLine("    {");
            sb.AppendLine("        None = 0,");

            int index = 1;
            foreach (var item in items)
            {
                string identifier = SanitizeIdentifier(item.Id);
                if (string.IsNullOrEmpty(identifier)) continue;

                sb.AppendLine($"        {identifier} = {index},");
                index++;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            string outputPath = settings.OutputPath;
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
            File.WriteAllText(outputPath, sb.ToString());

            AssetDatabase.Refresh();
            Debug.Log($"[ItemTypeGenerator] Regenerated {index - 1} items → {outputPath}");
        }

        private static string SanitizeIdentifier(string raw)
        {
            if (string.IsNullOrWhiteSpace(raw))
                return null;

            string cleaned = Regex.Replace(raw, @"[^a-zA-Z0-9_ \-]", "");
            var parts = cleaned.Split(new[] { '_', '-', ' ' },
                System.StringSplitOptions.RemoveEmptyEntries);

            var sb = new StringBuilder();
            foreach (var part in parts)
            {
                if (part.Length == 0) continue;
                sb.Append(char.ToUpper(part[0]));
                if (part.Length > 1)
                    sb.Append(part.Substring(1));
            }

            var result = sb.ToString();

            if (result.Length > 0 && char.IsDigit(result[0]))
                result = "Item" + result;

            return result;
        }
    }
}
#endif