// <auto-generated>
//     This code was generated by ItemTypeGenerator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace _Project.Scripts.Items
{
    public enum ItemType
    {
        None = 0,
        HealthPotion = 1,
        SpeedPotion = 2,
        Meat = 3,
        CommonRingMaxHealth = 4,
        UnCommonRingMaxHealth = 5,
        RareRingMaxHealth = 6,
        CommonRingRegenerationHealth = 7,
        UnCommonRingRegenerationHealth = 8,
        RareRingRegenerationHealth = 9,
        CommonSword = 10,
        UnCommonSword = 11,
        RareSword = 12,
        CommonArmor = 13,
        UnCommonArmor = 14,
        RareArmor = 15,
    }
}
